title: Eliza Plugin Docs
description: Everything you need to get started with Eliza Plugin!
theme: just-the-docs
color_scheme: eliza

url: https://just-the-docs.github.io

aux_links:
  Find us on Fab: https://www.fab.com/listings/e82dfb26-a9bb-4e98-8068-42c7e78f561e
  Github: https://github.com/CrucibleNetworksLtd/Eliza-Plugin-Unreal
